### ISSUE TITLE
Bug whit Polyglot

### ISSUE THREAD

**Issue by rinnocenti** [napolitanod/Token-Says#101]
![image](https://user-images.githubusercontent.com/3178127/221445884-1c5143d3-3cb8-4190-8f06-5cdbd1b1326e.png)
When I set a different language for a token to say something, it throws an error.

![image](https://user-images.githubusercontent.com/3178127/221445936-97c6b340-8785-4212-bcbd-1241030511d9.png)

**Comment by napolitanod** [comment]
Sorry for not responding sooner, I wasn't getting the notifications for new issues. I'll look into and address ASAP

**Comment by napolitanod** [comment]
This should be fixed now with 1.11.1 release
