### ISSUE TITLE
Trigger by how closely an attack hits or misses?

### ISSUE THREAD

**Issue by Quidam2k** [napolitanod/Token-Says#102]
I'd love to fill rollable tables with descriptions of close hits and misses for various weapons, including ones for solid hits and sorry misses.

Is there a way to set up a saying so that it will trigger any time an attack is made or save triggered and it was close or wasn't? Say one thing if the attack roll of 19 hits an AC of 18, another if a 25 does. If your they beat your save DC by five, have it say one thing, etc.

**Comment by napolitanod** [comment]
Hello - sorry for the delayed reply, I wasn't getting notifications for new issues. 

What system is this for?

**Comment by Quidam2k** [comment]
It's for 5e. Would love to be able to generate flavor text I can read as DM when weapons or spells hit or miss, or crit or badly miss. Can use gpt to come up with a bunch and have it spout a random one so I'm not using the same flavor text over and over.

**Comment by napolitanod** [comment]
I'll have to give this some thought. This module will not be determining degree of hit or miss. That is something that the dnd5e system does not calculate or provide. It would require a module that does do these calculations, such as MidiQol. from a Token Says standpoint I won't be managing that amount of code and keeping it in sync with MidiQol/dnd5e updates, but I may be able add in some hooks that can be used in your own macros/world scripts that you could utilize when whatever module you are using to determing hit/miss differential hits the threshold that you are looking for. I'll reply here once I think it through.

**Comment by napolitanod** [comment]
I'm closing this as out of scope for this module given how unique each system's damage/attack/etc rules are - I don't have the time or desire to support the various systems for which this request comes up as they each require their own custom handling. Another module author can develop a module to support this and can make use of the Token Says api to generate the saying - I'd be happy to answer questions from them on the Token Says API.
