### ISSUE TITLE
Action types: Condition/Effect and Critical Hit/Fumble doesnt work on PF2e

### ISSUE THREAD

**Issue by ZzinnerGamer** [napolitanod/Token-Says#104]
As the title says, those options doesnt work at all in PF2e having just Token Says module running in the system or with other modules.

**Edit**: Damage rolls doesnt work either.

[not working.webm](https://user-images.githubusercontent.com/57156790/227661307-16040317-1943-49f1-b4af-c3d024ebcad8.webm)

**Comment by ZzinnerGamer** [comment]
About the fumble, i see that failing a check generates the saying but critting it does not.

[fumblecrit.webm](https://user-images.githubusercontent.com/57156790/227671797-f7a7608c-8ae0-4acc-aa0f-7c65f5113724.webm)

On the effect thing, im not a developer, neither a java scripter, just a user, and a recent one specially in pf2e, but what i could think, that effects are just items added to the actor.
What i can think about,, because of the nature of how it works on adding effects, is that it register the changes in the actor so it shows the tooltip that the effect has been added, how monks tiles does it in the scrolling text option:

[scrolling.webm](https://user-images.githubusercontent.com/57156790/227671727-ec34f225-12ea-437c-8b01-4915780ee3a8.webm)

Effects are real items in compendiums that in chat are highlighted on chatrolls so it can be dragged to the actor in scene.
I dont if my hypothesis could help you at all, sorry :c

**Comment by ZephyrS8** [comment]
Critical Hits used to work, up until version Pathfinder 4.7. I am wondering if they have changed some naming in their code.

**Comment by napolitanod** [comment]
It does look like they updated their handling on the crit. Try it with the latest Token Says release and let me know if it works as you would expect.

**Comment by harrisog** [comment]
> The effects are another thing. I recently learned that PF2E doesn't use the Foundry active effects which is what that is generated from. Do you know how effects work in Pf2e in terms of data structure? If not, I'll just pull that option out from pf2e.

Checking in after encountering this bug -- have you tried asking around the pf2e channel in the Foundry discord? Surely someone there would know what's up with conditions. Would hate to see this feature go by the wayside!

**Comment by DianeOfTheMoon** [comment]
I poked around in code, and pf2e now uses effects as items, so you have to hook into createItem and deleteItem.  I have some code I'll put up a PR for that seems to work if you'd like.

**Comment by DianeOfTheMoon** [comment]
Might be worth creating issues for each type of data that doesn't seem to work correctly with pf2e and I can go digging for what might be going on.

**Comment by napolitanod** [comment]
I'll take a look at the pull request. My time has been limited

**Comment by napolitanod** [comment]
I used the pull request and made some small changes. Please give it a test with the new version.

**Comment by DianeOfTheMoon** [comment]
Oh, if you're going to re-implement, you'll also need to check a documentType of "condition".  I wasn't sure how you would want to structure the code, so just checked effects.

**Comment by napolitanod** [comment]
Thanks for the additional info. I'll have conditions included in the next release.

**Comment by napolitanod** [comment]
I think this is all complete with the most recent version which includes condition
