### ISSUE TITLE
[Feature request] Add a macro to check/uncheck option: Activate Token Says

### ISSUE THREAD

**Issue by GregorHak** [napolitanod/Token-Says#105]
Can You Add a macro to check/uncheck option: Activate Token Says
![obraz](https://user-images.githubusercontent.com/99994770/227784651-dfb77e5d-329e-42f8-b00c-3098ec4e10cf.png)

I want add it to shortsbar
![obraz](https://user-images.githubusercontent.com/99994770/227784814-1e5c0978-014b-4ac8-b61d-286e0cd820fd.png)

**Comment by napolitanod** [comment]
I have added a toggle to the API with Token Say v 1.11.2. Try tokenSays.toggleActivate() in your macro

**Comment by GregorHak** [comment]
Nice, In Compedium Packs I spotted folder "Token Says Macros", but it is empty, you can add this macro for others. Thanks!

**Comment by napolitanod** [comment]
The compendium pack should be populated again, that probably broke going into v10. I added a macro into it for the toggleActive
