### ISSUE TITLE
 [Feature request] Allow token/actors names be not complete

### ISSUE THREAD

**Issue by GregorHak** [napolitanod/Token-Says#113]
Can you add option to allow token/actors names (in Token speaking options) be not complete, and then choose multiple token/actors with the specified word in name. Smillar like works Wildcard Token Images in Foundry.

Soo, eg. If I type *Goblin*, token says will be work for all tokens/actors with a word "Goblin"

![obraz](https://user-images.githubusercontent.com/99994770/230743370-81946927-19bc-4831-aa16-ca286a7bcfe5.png)

**Comment by DianeOfTheMoon** [comment]
@napolitanod Would a regex filter for these name fields and surround with `^$` to keep existing functionality sound good?

**Comment by GregorHak** [comment]
Sounds fine, I will try it when update goes live

**Comment by GregorHak** [comment]
Ok found a thing. Responds to Conditions not work when option "Use Actor Name" is unchecked (like on the image below). When Check option "Use Actor Name" working well. Tested also Responds to Token movement end and working well with both Check/Uncheck option "Use Actor Name" 
![obraz](https://user-images.githubusercontent.com/99994770/235874994-f9c86d6c-b663-4c4f-8820-418ac17d159c.png)
