### ISSUE TITLE
Responds to Conditions with "Use Actor Name" for WFRP4

### ISSUE THREAD

**Issue by GregorHak** [napolitanod/Token-Says#118]
If "Use Actor Name" is unchecked for Responds to Conditions then do not work. To work with Conditions option "Use Actor Name" must be always as check.

I use WFRP4 system and foundry v10
I starter thread here: https://github.com/napolitanod/Token-Says/issues/113

**Comment by napolitanod** [comment]
The cause is likely the WFRP4 system. I'm not familiar with it and some systems will not use active effects for conditions. My time has been very tight lately but I'll look into the system when I have a momenet.

What is the system actually called so I can find it? Or is the acronym WFRP4 the name?

**Comment by napolitanod** [comment]
Good morning,

I tried this in my limited setup of warhammer 4e with just basic actors. I tried various settings of wildcard/not wildcard, actor name/not actor name on both the responds tab and the basics tag. In each instance the saying is generating when adding the Dead condition. The only difference aside from name on between our settings (I looked at the screenshot you provided on the linked issue) is that I use the | separator and not a comma. Do you have other scenarios where this works? Perhaps with non-characters or not using the Dead condition?


![wh4eCondition](https://user-images.githubusercontent.com/22696153/236689604-203cf553-0c92-4c9a-94c6-b439638f8999.gif)

<img width="314" alt="image" src="https://user-images.githubusercontent.com/22696153/236689596-3f54deb7-16a7-4c8c-b728-826bfd4cd9ac.png">

**Comment by GregorHak** [comment]
I tested again, and do not know why not working. I test both player character sheet and Non-player character. Now when tested again I fix problem due temporary change audio file (I use empty chat bobble and sound). Now works well, maybe due module update problem occurs, also as my wildcard I use emoji text like 🫡, 🧟 and ◽ . So all players and allies have in token name ◽ <-- this emoji, so enemies can react only to players and their allies.

So finally works, very much to your time!!!
