### ISSUE TITLE
[Feature request] Say Crits on spell PF2E

### ISSUE THREAD

**Issue by Steelskinz** [napolitanod/Token-Says#127]
It seems that the Crits only apply when the " Critical " button is pushed, which is not available for spellcaster. However it is possible to crit as a spellcaster if the AC is passed by 10 or more. Is it possible to make it work somehow ?

**Comment by napolitanod** [comment]
There's other outstanding requests for pf2e handling that are like this and getting deep into the system-specific rules. I do not have the capacity to extend Token Says to cover any game system extensively and to maintain it over any API changes that system makes. Making the current crit work for pf2e was a stretch :). If you or somebody that you know wants to take on building a sub-module for pf2e I can work with them to provide what API they need to integrate with Token Says. They would just have to cover the code that triggers token says when these types of events (e.g. spell crit, death, loss of HP, whatever else) occur and then I can make the Token Says API available for them to call.
