### ISSUE TITLE
[Bug PF2E] Chat Message won't appear

### ISSUE THREAD

**Issue by Wotn9** [napolitanod/Token-Says#129]
Only tried on PF2E, but Chat message won't appear, this is a fresh server, with no module on : 
![image](https://github.com/napolitanod/Token-Says/assets/45216414/93c4f9e8-aebf-45a4-b485-a5eb59afe542)
![image](https://github.com/napolitanod/Token-Says/assets/45216414/e1104f2b-558c-4f68-8ab4-74d631e7a9c4)

Easy to reproduce, put a message in Token Says and able to post in Chat Message.

**Comment by napolitanod** [comment]
Thank you for reporting. Looks like a bug I introduced with the 1.12.1 release whisper feature. Please try the latest (1.12.2) release. I think it should be fixed.

**Comment by Steelskinz** [comment]
You're so fast I was about to post about my duck-taped fix haha. All working now.
