### ISSUE TITLE
[Compatibility] Broken compatibility with Polyglot 2.1.7 (Foundry v11)

### ISSUE THREAD

**Issue by DarknesSeeker** [napolitanod/Token-Says#133]
I recently updated to Foundry v11 and while updating my modules I realized something seems to have broken between TokenSays and Polyglot:

1. Languages in the saying menu appear as "[object Object]" instead of showing the language.
![image](https://github.com/napolitanod/Token-Says/assets/32309040/0f9a30eb-26d4-4d74-88e4-fe2b4b8669ad)
2. Any saying that has one of these languages selected is seemingly deactivated: No matter how is provoked, they won't fire at all. Once you remove the language they work as intended.
3. This error doesn't leave any message nor warning whatsoever in the console log.

I remember back in v9 there were some problems bethween the modules, but at least there was a silver-lining of warnings and errors to track what was happening.

Thanks for the attention!

**Comment by weepingminotaur** [comment]
Getting this error as well.

**Comment by napolitanod** [comment]
Looks like Polyglot updated the structure for the language object. I believe I have updated my code correctly to handle their change. Please try with 1.12.3 release
