### ISSUE TITLE
Feature Request - Volume Controls

### ISSUE THREAD

**Issue by Golurkcanfly** [napolitanod/Token-Says#20]
Some SFX people may use are of varying volume, and a volume slider that lets you adjust each individual audio clip's volume would be excellent.

**Comment by napolitanod** [comment]
Absolutely. I'm working through an enhancement with one of my other modules and will do this after. Thanks for the suggestion!

**Comment by napolitanod** [comment]
I just pushed 1.0.3 release which includes the ability to set the volume for each audio saying. Please check it out. Thanks for the suggestion!
