### ISSUE TITLE
Feature request: variables

### ISSUE THREAD

**Issue by diannetea** [napolitanod/Token-Says#23]
If this already exists I couldn't find it, but I'd like a way to use variables in the roll table sayings to be used across multiple actors for fancier formatting (in particular the token's name, but also maybe other variables would be useful e.g. when using responses the name of the token targeting them or the attack/weapon name being used)  I'm just using % as a generic variable symbol in my examples, honestly anything here would be fine.  %token% or ~token, whatever works and is easy to implement.

Basic name variable format:

`%token says, "Hey, that hurt!"`

and it would appear in the chat as:

`diannetea says, "Hey, that hurt!"` or `Britney says, "Hey, that hurt!"`

Advanced ones would be really neat, but it might be too much of a PITA to implement (especially making punctuation show up properly, though maybe a regex to check for any symbols to remove a space between them could work):

`diannetea fails to parry with her %itemid .  She grunts as the %attacker.name 's %attacker.item hits her.`

so it would show up something like

`diannetea fails to parry with her Super Fancy Sword.  She grunts as the Goblin's Boring Cudgel hits her.`

I just wanted to add, I realize I can do this with macros, but this would be a faster, easier format for those less savvy at javascript or those lazy like me 😂

**Comment by napolitanod** [comment]
great idea - I'll add this to the projects board!

**Comment by napolitanod** [comment]
Hello! I took a first pass at this, introducing those things from the roll that were already available to me: alias (token name), actor (actor name) and item name. If the saying is in response to another saying or to an action, you can grab the data from the action that triggered the response by preceding with r_. The format would be like [@alias] or [@r_alias].

Let me know if you hit any snags!
