### ISSUE TITLE
Im struggling to get this to trigger off anything other than attack roll

### ISSUE THREAD

**Issue by dmoreland** [napolitanod/Token-Says#31]
I'm trying to get this to trigger from the casting of spell but I'm not succeeding, my example is Bards Vicious Mockery. But i can only get the plugin to work off attack rolls.

**Comment by napolitanod** [comment]
Good morning,

Please give the Action Type a look. Is it set to Item Name? See example pasted below which works in my set up. For spells, they do not perform an attack, so will not trigger off of an attack roll action type. 

If this isn't it, after checking spelling/caps and Action Type, please let me know and let me know if you are using any rolling modules (e.g. better rolls or midi-Qol). I am assuming that this is dnd5e, given vicious mockery, but let me know if not.

![image](https://user-images.githubusercontent.com/22696153/139884434-ac73dc95-b50e-450b-8309-0f62ed2a32a4.png)

**Comment by dmoreland** [comment]
Ok i just tested and this works if i disabled better rolls for 5e but not with it enabled.

**Comment by napolitanod** [comment]
Thanks for the info. I'll dig into what Better Rolls is doing to manipulate the data being passed along. I should be able to add handling for it. Will be back in touch here when I push out a fix.

**Comment by dmoreland** [comment]
you are awesome and my Bard is very happy :)

**Comment by napolitanod** [comment]
I just pushed out 1.4.2 release. Please update the module and give this a shot. Will still need to reference item name for vicious mockery.

I think the other types are now working for better roll also (saves / checks / etc) except for damage, which I will need to spend more time on working out an approach and understanding how better rolls handles this data.

Thank you for bringing this to my attention. Please reopen ticket if it actually isn't solved.
