### ISSUE TITLE
[Feature Request] Add the click an the double click on the list of actions type

### ISSUE THREAD

**Issue by p4535992** [napolitanod/Token-Says#47]
I wish I could have a list of sounds and messages randomized to the click and double click event on the token. Is it possible to add these events to the dropdown list of the actions type available?
Below is an example code for integrating with libwrapper, but you are definitely more experienced than me.

```
// Click
libWrapper.register(
    moduleName,
    'CONFIG.Token.objectClass.prototype._onClickLeft',
    game.tokenSays.saysDirectOnClickLeft(),
    'MIXED',
  );
// Double click
  libWrapper.register(
    moduleName,
    'CONFIG.Token.objectClass.prototype._onClickLeft2',
    game.tokenSays.saysDirectOnClickLeft2(),
    'MIXED',
  );
```

**Comment by napolitanod** [comment]
Hello! This was requested by somebody else also and I plan on doing it for the next update. Thanks for the libWrapper code that is very helpful!

**Comment by napolitanod** [comment]
I started thinking through this. Having sayings respond to click/double click may be somewhat restrictive. For example, the DM couldn't trigger sayings in this way without also selecting or opening the character sheet for tokens when doing so (if I am thinking about this correctly).

I'm thinking through methods that would have consistent results across users. Would a keybind be an adoptable solution? Such as P or Alt+P (P for prompt). I can't use T for talk or S for say because these do things already to tokens.

**Comment by p4535992** [comment]
let's say that at least for me (I don't know the others who have expressed this need to you), even just something to call at the API level would be enough to generate the chat, or the sound, or the chat with the sound.  So click, double click or keybind can be decided at macro level the idea would be to have commands like these:

```
game.tokenSays.randomChat(token, options) // options are things like type of language or specific text
game.tokenSays.randomSound(token, options), //options are things like playlist name or sound name, ecc.
game.tokenSays.randomChatAndSound(token, options),
```
maybe this mode can be more generic on your side?

**Comment by napolitanod** [comment]
Somebody else wanted some form of token prompt so I will be doing it, just unsure of design.
Have you looked at/tried the existing API calls within macros? There is .says(), which lets you run any saying that you have defined and then there is .saysDirect() which lets you generate a saying without having previously defined it. The latter includes some options but I need to build it out further to support some recent additions (such as audio/text combined). These are detailed in the main page / helpme

**Comment by p4535992** [comment]
yes I had seen the existing API,  it was just to give you an example of what I needed, I just saw in version 1.7.0 the feature "Sayings can now do both audio and chat message / bubble at the same time." , so it should be just fine for my use case.
I will give a try.

**Comment by napolitanod** [comment]
Hello,

I have added prompt actions that I think will address this need. When on token layer, hover over a token and press 'P' or Shift+P. This will trigger any saying associated to that token of type 'Prompt' or 'Prompt Other'.

These are added as keybindings so I believe you can change it from P to something else via the keybind config in foundry

Thanks!!
