### ISSUE TITLE
Potential bug? Rollable Table Sayings and Audio File Sayings cannot work together?

### ISSUE THREAD

**Issue by ArdonDaros** [napolitanod/Token-Says#48]
Hello!

Hello. I noticed that Rollable Table Sayings and Audio File Sayings cannot work together? Is this a bug or a feature? What would it take for them to be allowed to work together? For instance, I have flavor text when a token dies, and I'd also like to play a sound effect to accompany it. Right now, when a token gains the condition "Dead" it only plays the rollable table text, but never the sound file. The sound files are set properly, as they do play if I change the condition to say, "Bleed".

**Comment by napolitanod** [comment]
Hi! Thanks for using the module.
This isn't a bug - it's also not a desired 'feature'. More of a limitation in the design that goes back to how I initially wrote the code. In the event that there is overlap between 2 or more sayings when being triggered, only one will win out. There's some ranking involved as to which is selected, but the end result is that you cannot do what you want to do in the above scenario.

In some situations it is a good thing. For example, if you have a generic attack saying for a token and then you add a second attack saying for that token for when they use sword, the sword saying should win out over the generic one and you won't get overlapping chat bubbles or chat message spam. The downside to (current design) is that it can't do both a text and audio at the same time.

All that said, I did a large rewrite of the code in one of the more recent releases and am closer to being able to support multiple sayings for one trigger. So the ability to do this will be coming at some point. I will inform you via this ticket when it is done.

**Comment by ArdonDaros** [comment]
Fair enough! Thank you for the speedy message. I look forward to when both triggers can work together! Thank you for the amazing module!

**Comment by napolitanod** [comment]
Release 1.7.0 implements the ability to have a saying play both audio and text chat messages/bubbles at same time. Basically I combined the two types into one so in one form you just set up both parts. Your existing sayings can be modified to make use of this change.

The overall limitation of playing 1 sayings per provoking action still applies so if 2 sayings meet a condition only 1 will still play.
