### ISSUE TITLE
When rolling multiple attacks with sounds being pulled from commpendium it crashes

### ISSUE THREAD

**Issue by subatoiWolf** [napolitanod/Token-Says#5]
If i use multiple attacks drawing from an audio playlist in commpendium the token dissapears and foundry freezes.  This is an awesome idea for a module!!! It would be great for me because i have a whole bunch of audio files for monsters.  I am using midi, monks token bar and a crap load of other modules so its probably my fault.  Really like this module!!!!!

**Comment by napolitanod** [comment]
Hello!

Thank you for using this module. I attempted to recreate your issue and I cannot get my foundry to crash. I also use midi and monks and I tried with and without the dnd5e multiattack module (up to 8 attacks run in quick sequence playing an audio file from my compendium). There may be some causes the discrepancy between our experience. Can you please answer as much as the following as you can:

- what Foundry system does this happen in?:
- what Foundry version are you currently on?:
- are you hosted? If so, through what hosting service?:
- what browser (if applicable)?:
- how long is the audio file that is being played?:
- roughly how many attacks are involved in multiattack? Are you using a specific module to perform the multi-attack?
- Finally, if you are able to capture any errors directly after you experience this that you see in the developers console (will be in red furthest down the list) (F12 in your browser or app) please attach a screenshot or copy of that. 

This information will help me recreate my set up like yours. The F12 dev console info is particularly useful in identifying the culprit. Also know if it occurs with just Token Says as the sole module.

**Comment by napolitanod** [comment]
no response
