### ISSUE TITLE
Chat Bubble messages are always in common instead of the selected language.

### ISSUE THREAD

**Issue by Ssezra** [napolitanod/Token-Says#51]
It would appear that any language assigned to a saying via chat or audio always produces a common chat bubble. (sourced from a roll table)  Chat messages appear correctly as jumbled jargon.  Polygot used by itself displays the chat bubble and chat message in the correct jumbled jargon  ( ie a character doesnt know the language being spoken)

**Comment by napolitanod** [comment]
Hmm, this was working at some point previously. Let me take a look at what changed. Thanks!

**Comment by napolitanod** [comment]
I put a ticket in with Polyglot. Not sure if it is on their end or mine but I can't seem to get the chat bubble to translate following their guide. Note that I can get polyglot if I entered a chat message. The situation at play here is when only a chat bubble is generated which is how I go about it under all circumstances (https://github.com/League-of-Foundry-Developers/fvtt-module-polyglot/wiki/Macros).

**Comment by napolitanod** [comment]
Okay, this should be fixed with the most recent update (1.7.1). You will also need the new Polyglot update.

Please let me know if that addresses it.

**Comment by Ssezra** [comment]
Everything looks good to go now. Chat Bubbles and Messages are now encoded correctly when a player doesn't know the language. Thank you for looking into this matter and getting it corrected. It is appreciated.
