### ISSUE TITLE
FEATURE: Not Actor

### ISSUE THREAD

**Issue by galaara98** [napolitanod/Token-Says#66]
can you add support for !Actor in the list of Actors (specifically responds to)

say something when someone moves within sight of 30ft but !Jerry

**Comment by napolitanod** [comment]
Yes, I can basically make it reverse, so saying will play for any token triggering unless its one of the listed names. I can do for responses also.

**Comment by napolitanod** [comment]
I added this feature to 1.9.0. Please try that out and let me know if it is working for you.

Thanks!

**Comment by galaara98** [comment]
Wow, i will check that out when i get home.
