### ISSUE TITLE
Playing Audio from a Playlist in a Compendium

### ISSUE THREAD

**Issue by Armandeus66** [napolitanod/Token-Says#75]
I have this problem.
I have a compendium of sounds (Compendium A) to draw from for Token 1. I choose an action (=movement end) and want to set a single sound to play once. Only one sound from the compendium should play, and it should always be that same sound. There are several playlists in the compendium (for organization purposes - because Token 1 also has some actions which draw a random sound from Playlist Z in Compendium A).
I go to the audio tab and enter the compendium name, Compendium A. The sound I want is in Playlist X, so I enter the name of the playlist. I then enter the name of the sound, Sound Y.
What happens is, when Token 1 finishes a move, a random sound from Compendium A Playlist X plays, instead of always Sound Y, which is what I want to happen.
I tried remedying this by deleting the information "Playlist X" in the entry, but leaving the text in entries for Compendium A and Sound Y. However, if I do that, no sound plays at all when the triggering action occurs.
What am I doing wrong?
(I did see "random, etc." under Play for the Chat tab, but I did not specify any text to be shown in a speech bubble or chat. Does this entry affect audio as well and not only chat text?)
The setup is like this:

Token 1

Compendium A (with all of the sounds Token 1 will need)
--Playlist X (with sounds to trigger individually and not at random)
----Sound Y
----(other sounds)
--Playlist Z (with sounds to trigger randomly from this list)
----(other sounds)

I have watched the tutorial video, but I don't think it answers my question.

**Comment by napolitanod** [comment]
Thank you for the report. I should have time in the next week to have a look at the issue and address it.

**Comment by napolitanod** [comment]
Sorry for the delay - just moved homes. This should be fixed with 1.9.4. Please give a shot.

**Comment by Armandeus66** [comment]
Thank you! I will try it out soon.

**Comment by Armandeus66** [comment]
It is working fine now, thanks!
