### ISSUE TITLE
Setting Up Responds to Damage/Healing

### ISSUE THREAD

**Issue by Armandeus66** [napolitanod/Token-Says#78]
How do I set up "responds to" damage/healing applied to the responding token by any other token?

I want a token to say something when it is damaged or healed, not specific to any token doing the damage/healing.

I thought it was "damage roll" but every token in the scene set for this responds to any damage roll even if they are not targeted.

**Comment by napolitanod** [comment]
That type of functionality crosses over into Target Reacts module territory. Please check out that module and see if it handles your situation. Target Reacts eacts handles the domain of an actor reacting to something done unto it.

**Comment by Armandeus66** [comment]
OK, I'll try that. The fact that it seems to require MIDI QOL, a D&D5E module, might be a problem because I am using PF2E.

**Comment by napolitanod** [comment]
I'm closing this as out of scope given how unique to a specific system. If an author wants to establish a pf2e sub module to support this Token Says has an API that can be called to generate the saying.
