### ISSUE TITLE
[Feature Request] Respect Draw with Replacement Option for RollTable

### ISSUE THREAD

**Issue by SKullDugDev** [napolitanod/Token-Says#79]
My use case is such that I have a Token who says Fortunes from a RollTable rolled randomly. However, I would like each fortune to only be told once. That is, I would like it so that Token Says has an option when playing randomly off a Table to respect the "Draw with Replacement" option such that if it is on, Token Says will not roll the same roll more than once.

**Comment by napolitanod** [comment]
Hello! I am working on the v10 Foundry updates now for Token Says. This requested feature will be available in Token Says 1.10.0 which will be available once v10 Foundry is production ready.

Thanks!

**Comment by napolitanod** [comment]
Closing this now that v10 is live. This should work with the appropriate setting in foundry v10
