### ISSUE TITLE
Multiple condition ?

### ISSUE THREAD

**Issue by Steelskinz** [napolitanod/Token-Says#80]
Hey, me again (Oh noes.). I hope you're doing fine in your new house ! 
Here's my question : Will it be possible to trigger text under multiple condition ? 
Example : 
One of my player got a certain curse mechanic, like lycanthropy, and he asked me if it was possible to switch "Turn" says only when he was transform. I suck at coding but I think this might be way too much messy to achieve, even in the concept. 

However I think it would be nice that if you have a condition (Example, Old god item that curse you) and sometimes sentences pop up because you have this condition at the start of your turn. 

Example : 
- " I will fight with honor ! " 
- (Cursed by the item, another sentence appear) _" And you will fail... "_ 

Last question, I haven't check when I write this message but can we apply an Active Effect to the conditions ?

**Comment by napolitanod** [comment]
Hello!

Active effects when added removed should also generate a saying set up for condition add or remove.

As far as conditional sayings based on another data point - I can add a limit to make it so the saying only triggers if certain effects/conditions are on the character - I'll work on that for the next release of Token Says which will be tied to Foundry v10. 

Beyond that it may get too complex but there are other options. The token name can be updated when they transform to indicate that they are now in lycanthrope form. Another option is to utilize the macro generated by a saying - so have a turn start saying generate and then have that tied to a macro which could perform whatever other logic is required to determine if another saying should be generated and have that macro call the other saying if the condition is met.

**Comment by Steelskinz** [comment]
Gotcha Thanks for your hardwork and quick answer ! I'm looking forward to v10 then ! Until then have a gooday!

**Comment by napolitanod** [comment]
Closing this now that foundry v10 is live. This should work once you update to v10 and get the token says version on that.
