### ISSUE TITLE
User lacks permission to update token in parent scene

### ISSUE THREAD

**Issue by iamthehorker** [napolitanod/Token-Says#81]
I get this error when a player triggers a saying via the _Responds to_ provoking action. The npc tokens that are generating the sayings have a limit set to 1. It appears that some sort of macro(?) is being generated by the player after triggering the saying to update the npc token's saying count, but the players don't have permissions to edit the tokens so it fails.

The error goes away if I set the npc tokens as owned by the player (not ideal), or if I trigger the saying as the GM.

**Comment by napolitanod** [comment]
I think I have corrected this issue with 1.9.5. A little hard for me to fully test because I am working on the v10 version. Please let me know after update to 1.9.5 if the issue persists.

thanks!
