### ISSUE TITLE
[Feature Request] Add config option for Actor Types

### ISSUE THREAD

**Issue by OmnesPotens** [napolitanod/Token-Says#86]
I would like to be able to limit sayings to only trigger for specific Actor Types (while maintaining Token/Actor name restrictions if they are filled in).

**Comment by napolitanod** [comment]
Yes, I'll add this for the Foundry VTT v10 branch.

**Comment by napolitanod** [comment]
Closing this now that foundry v10 is live. This is available in foundry v10 and latest Token Says release.
