### ISSUE TITLE
[Feature Request] Support Token Drag Movement Action

### ISSUE THREAD

**Issue by git-ival** [napolitanod/Token-Says#87]
In some scenarios it would be ideal to only start playing a sound when token movement is performed via dragging. 

For example: I want a sound for footsteps to play when I finish dragging my token to the desired location (and not stop until the sound reaches the end of the file). But I do not want this sound to play for the more general "Token Movement Start/End" actions.

**Comment by napolitanod** [comment]
I'll see if the hook informs whether it is a drag or other action. Another option would be to present a estimated token movement minimum time box that you could put the ms into and anything beneath that time would not play or could optionally play a different sound file that is not truncated (such as a short footsteps files).

**Comment by napolitanod** [comment]
I didn't go with a drag action on this one. Instead, I added to the saying form a minimum time option for the movement start action type where, if the estimated time it will take for token to move from point A to point B is less than the minimum, the audio track will not play. I also included an place to put an alternate audio track that could be played instead should the minimum no be met (e.g., a couple of footsteps)
