### ISSUE TITLE
Bubble chat issue V10

### ISSUE THREAD

**Issue by Steelskinz** [napolitanod/Token-Says#95]
2 types of issues : It don't show as it should or It never get away as it should.
How to reproduce : Make a simple Token Says like you would, activate the trigger for it and the issue should appears.
![image](https://user-images.githubusercontent.com/93941729/190529076-f0859d75-13f1-45e4-9dec-fa20b6b74c39.png)

**Comment by napolitanod** [comment]
I'm not getting the errors in the console but was seeing inconsistency with bubble placement. With the latest release 1.10.2.5 I have changed to using the new bubbles.broadcast() method that was introduced in v10 Foundry which seems to address the placement issue that I was seeing. Can you please see if this addresses the error you are getting? 

It seems that Polyglot module, if you are using, is not translating the bubbles so I need to address that in the next release.

**Comment by Steelskinz** [comment]
Nope no more error, we all good and the bubble works perfectly, thanks for your hardwork !
