### ISSUE TITLE
Help with a Macro

### ISSUE THREAD

**Issue by Armandeus66** [napolitanod/Token-Says#99]
I want to trigger two sounds in sequence, the second one random, when a token's turn in combat comes up. The random voice sound is set to play from a compendium playlist.

I tried making two Turn in Combat sayings (one for the short music sound, and one with a delay until the end of the music that plays a random voice sound), but only the voice sound with the delay plays.

I see you can list sounds in sequence for one saying, but can you do it for this case (one sequential, one random, same saying/trigger)? Sequential and random seem mutually exclusive.

If not, can I do it with a macro? If so, can anyone show me an example of this macro?

Thanks!

**Comment by napolitanod** [comment]
If I'm recalling correctly, one event will only generate one saying for a token. With the turn start event, if there are 2 or more sayings that the token qualifies for, only one will trigger. This is to make is so you can set up a saying for any attack and a saying for sword attack and then when the token attacks with a sword only the sword attack saying generates as opposed to both. 

I'll consider implementing a method to allow for overriding this behavior for a saying. In the meantime, you can certainly do it in a macro:

**You must have the Advanced Macros module installed**. It's a fairly common module so you likely will have it already.
- Create a new script macro and name it whatever you want. For purposes of this instruction I'll call it 'Token Says Macro Example'
- Add ```tokenSays.says(args[0].token.id, '', 'Name of your second saying that you want to trigger')``` to the macro body and save
- Update the saying that you are triggering first based on turn start, go to the Trigger tab and the post trigger macro field and select the 'Token Says Macro Example' macro from the list.
- Update the second saying (the same one that you put into the macro 'Name of your second saying that you want to trigger' spot) and change the action type to 'Macro (API)'.


That should do it. Basically the first saying will trigger the second saying via the post trigger macro by calling the Token Says .says() API call. That call intakes a token id, an actor id, and the name of the saying to call. Token id or actor id can be blank but one must be provided. The saying being called must be of type 'Macro (API)'. Where you see ```args``` within the macro code I provided, this is what Advanced Macros assists in passing in. if you check out args (by adding console.log(args) to the macro that is called) you will see the other stuff provided for use in the post trigger macro

**Comment by Armandeus66** [comment]
Thank you very much for your instructions.

I think I am trying to do something a bit different from what you explained, and since I don't know enough about macros, I would like to ask for some help, please.

Your example seems to be how to play a single sound after the first sound triggered by the event.

What I am trying to do is play a short music clip triggered by the start of the token's combat turn, immediately followed by one _randomized voice sound in a compendium_. The second part is why I need a macro, because currently the UI doesn't allow for a single sound followed by _a randomized sound_ on the same trigger.

What would such a macro look like?

Thank you!

**Comment by napolitanod** [comment]
Please update to the latest release 1.11.0 and try out the new 'Continues Saying' action type for the second saying that you want to generate. The 'Continues Saying' action type points to a different saying and will be generated when the other saying is generated. This means you can have an event trigger the first saying the the first saying generate the second saying (where the second saying is 'Continues Saying' and pointing at the first. 

There isn't a concept of how long it takes for a saying to generate - the second saying won't know when the audio of the first saying completes - so you'll need to set the delay appropriately for the second saying so there is a pause before it begins playing.

Please give that a shot

**Comment by Armandeus66** [comment]
Thank you!
